apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: castle_app_production
  POSTGRES_USER: castle-app
  POSTGRES_PASSWORD: XgbLL3MM7DO9Zi#kwS2R
